import { Employee } from './Employee';

export var EMPLOYEELIST: Employee[] = [
  {
    emp_id: 'XYZ-014',
    emp_first_name: 'Paul Vincent',
    emp_middle_name: 'Lao',
    emp_last_name: 'Jor',
    emp_address: 'Digos City',
    emp_contact_number: '09197865864',
    emp_office: 'CET',
    emp_position: 'Web Developer',
    emp_salary: 42000.1,
  },
  {
    emp_id: 'EFG-099',
    emp_first_name: 'Aldriahn Jay',
    emp_middle_name: 'Paring',
    emp_last_name: 'Jamio',
    emp_address: 'Davao City',
    emp_contact_number: '0922586934',
    emp_office: 'CEDAS',
    emp_position: 'Programmer',
    emp_salary: 38000.75,
  },
  {
    emp_id: 'YLI-031',
    emp_first_name: 'Charlene',
    emp_middle_name: 'Gallardo',
    emp_last_name: 'Saliot',
    emp_address: 'Gensan City',
    emp_contact_number: '09512514145',
    emp_office: 'CABE',
    emp_position: 'System Analyst',
    emp_salary: 40000.5,
  },
  {
    emp_id: 'ABC-032',
    emp_first_name: 'John Michael',
    emp_middle_name: 'Selim',
    emp_last_name: 'Porras',
    emp_address: 'Sta. Cruz',
    emp_contact_number: '09095658745',
    emp_office: 'CEDAS',
    emp_position: 'Graphic Designer',
    emp_salary: 37000.8,
  },
];
